import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";
import { DrinkList } from "../components/DrinkList";
import { useState } from "react";
import { TextInput } from "../components/TextInput";

const Drinks: NextPage = () => {
  const drinks = api.drinks.getDrinks.useQuery();
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [search, setSearch] = useState("");
  const { data } = api.drinks.getCategories.useQuery();

  const filteredDrinks = (drinks.data ?? [])
    .filter((drink) =>
      selectedCategory.toLowerCase() === "all"
        ? true
        : drink.category?.toLowerCase() === selectedCategory.toLowerCase()
    )
    .filter((drink) =>
      search != ""
        ? drink.title.toLowerCase().includes(search.toLowerCase())
        : true
    );

  return (
    <>
      <Head>
        <title>Drinks</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen">
        <section className="container mx-auto py-10">
          <h1 className="text-center text-2xl font-bold md:text-left">
            All Drinks
          </h1>
          <form>
            <div className="flex flex-col gap-3 px-2 md:grid md:grid-cols-3">
              <div className="col-span-1 flex flex-col gap-5 py-3">
                <TextInput
                  label="Search by Name"
                  onChange={(e) => setSearch(e.target.value)}
                  value={search}
                  required={false}
                  inputMode="text"
                />
                <div className="flex snap-x flex-row gap-2 overflow-x-auto md:flex-col md:gap-1 md:overflow-auto">
                  {(data || []).map((category) => (
                    <div key={category.id} className="form-control snap-start">
                      <label className="label cursor-pointer gap-1 rounded-md bg-slate-800 px-2 md:bg-transparent">
                        <span className="label-text truncate font-semibold uppercase md:font-normal">
                          {category.categoryName}
                        </span>
                        <input
                          type="radio"
                          name="radio-10"
                          value={selectedCategory}
                          className="radio checked:bg-accent"
                          onChange={() =>
                            setSelectedCategory(category.categoryName)
                          }
                          checked={
                            category.categoryName.toLowerCase() ===
                            selectedCategory.toLowerCase()
                          }
                        />
                      </label>
                    </div>
                  ))}
                </div>
              </div>
              <div className="col-span-1 grid auto-rows-max gap-4 md:col-span-2 md:grid-cols-2">
                {filteredDrinks.map((drink) => (
                  <DrinkList key={drink.id} {...drink} />
                ))}
                {filteredDrinks.length === 0 && <p>no drinks</p>}
              </div>
            </div>
          </form>
        </section>
      </main>
    </>
  );
};

export default Drinks;
