import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Button from "../components/Button";
import { api } from "../utils/api";
import { Select } from "../components/Select";
import { useEffect, useState } from "react";
import { useGetCategory } from "../hooks/useGetCategory";
import { Input } from "../components/Input";
import Image from "next/image";
import { Form } from "../components/Form";
import AccessDenied from "../components/AccessDenied";
import { toast } from "react-toastify";
import Spinner from "../components/Spinner";

const EditCategory: NextPage = () => {
  const { data: sessionData, status } = useSession();
  const { data: categories } = api.categories.getCategories.useQuery();
  const { refetch } = api.drinks.getDrinks.useQuery();
  const [categoryId, setCategoryId] = useState(34);
  const [formData, setFormData] = useState({
    categoryName: "",
    url: "",
  });
  const { category: productCategory } = useGetCategory(categoryId);
  const updateCategory = api.categories.updateCategory.useMutation();
  const deleteSingleCategory = api.categories.deleteCategory.useMutation();

  useEffect(() => {
    if (productCategory) {
      setFormData({
        categoryName: productCategory.categoryName,
        url: productCategory.url as string,
      });
    }
  }, [productCategory]);

  const handleCategoryUpdate = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await toast.promise(
        updateCategory.mutateAsync({
          id: categoryId,
          data: {
            categoryName: formData.categoryName,
            url: formData.url,
          },
        }),
        {
          pending: "Pending...",
          success: `${formData.categoryName} updated`,
          error: "An error occured 🤯",
        }
      );
    } catch (error) {
      if (typeof error === "string") {
        console.log(error);
      } else {
        console.log((error as Error).message);
      }
    }
  };

  const deleteCategoryHandler = async (id: number) => {
    if (window.confirm("Are you sure you want to delete this category?")) {
      try {
        await toast.promise(deleteSingleCategory.mutateAsync({ id }), {
          pending: "Pending...",
          success: `${formData.categoryName} deleted`,
          error: "An error occured 🤯",
        });
        await refetch();
      } catch (error) {
        console.log(error);
      }
    }
  };

  if (status === "loading") {
    return <Spinner />;
  }

  if (sessionData?.user?.role != "admin") {
    return <AccessDenied />;
  }

  return (
    <>
      <Head>
        <title>Edit Category</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mb-10 flex flex-col items-center justify-center gap-3">
        <div className="container mx-auto">
          <h1 className="my-5 text-center text-xl">Edit Category</h1>
          <div className="grid md:mt-5 md:grid-cols-2 md:gap-10">
            <section className="w-full px-3">
              <Form onSubmit={handleCategoryUpdate} width="md:w-100">
                <Select
                  label="Select a Category"
                  onChange={(e) => setCategoryId(parseInt(e.target.value))}
                >
                  {(categories || []).map(
                    (category) =>
                      category.categoryName.toLowerCase() !== "all" && (
                        <option value={category.id} key={category.id}>
                          {category.categoryName}
                        </option>
                      )
                  )}
                </Select>
                <Input
                  label="Name"
                  value={formData.categoryName}
                  onChange={(e) =>
                    setFormData({ ...formData, categoryName: e.target.value })
                  }
                  inputMode="text"
                />
                <Input
                  label="Image Url"
                  value={formData.url}
                  onChange={(e) =>
                    setFormData({ ...formData, url: e.target.value })
                  }
                  inputMode="text"
                />
                <Button
                  disabled={updateCategory.isLoading}
                  backgroundColor="bg-secondary"
                >
                  Save
                </Button>
              </Form>
            </section>
            <div>
              <div className="my-4 flex flex-col md:my-0">
                <p className="text-center text-sm uppercase">Category Image</p>
                <div className="relative h-64">
                  {formData.url && (
                    <Image
                      src={formData?.url}
                      alt="image"
                      fill
                      className="my-2 object-cover p-3 md:border-l md:border-primary-content"
                      priority
                      placeholder="empty"
                      sizes="(max-width: 768px) 100vw,
          (max-width: 1200px) 50vw,
          33vw"
                    />
                  )}
                </div>
              </div>
            </div>
          </div>
          <div className="my-5 flex flex-col items-center gap-2 md:w-1/2">
            <p>Delete whole category and all drinks associated?</p>
            <Button
              onClick={() => deleteCategoryHandler(categoryId)}
              disabled={updateCategory.isLoading}
              backgroundColor="btn-warning"
            >
              Delete Category
            </Button>
          </div>
        </div>
      </main>
    </>
  );
};

export default EditCategory;
