import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Drinks App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center">
        <h1 className="text-4xl font-bold">Drinks App</h1>
        {sessionData && <p>Welcome back {sessionData.user?.name}!</p>}
      </main>
    </>
  );
};

export default Home;
