import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {
  Alert,
  AlertDescription,
  AlertIcon,
  AlertTitle,
  Button,
  Center,
  Flex,
  Heading,
  Image,
  Spinner,
  VStack,
} from "@chakra-ui/react";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import nextI18nConfig from "../../next-i18next.config.mjs";
import { useTranslation } from "next-i18next";
import { api } from "../utils/api";

export const getServerSideProps = async ({ locale }: { locale: string }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"], nextI18nConfig, [
      "en",
      "sr",
    ])),
  },
});

const Home: NextPage = () => {
  const { t } = useTranslation("common");
  const { data: storeData, isLoading } = api.settings.getStore.useQuery();

  const buttonActions = !storeData
    ? "Visit Settings"
    : t("elements.button.view_all");

  if (isLoading) {
    return <Spinner />;
  }

  return (
    <>
      <Head>
        <title>{storeData ? storeData.name : "Drinks App"}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        width="100vw"
        height="100vh"
        alignContent={"center"}
        justifyContent={"center"}
      >
        <Center>
          <VStack spacing="5">
            <Heading>{storeData?.name ?? "Welcome"}</Heading>
            {!storeData && (
              <Alert status="warning" rounded="md">
                <AlertIcon />
                <AlertTitle>No stores</AlertTitle>
                <AlertDescription>
                  There is not a store added yet. Go to Settings to add a store
                  name and logo.
                </AlertDescription>
              </Alert>
            )}
            {storeData && (
              <Image
                alt="logo"
                src={storeData.logo}
                boxSize="sm"
                rounded="md"
                objectFit="cover"
              />
            )}
            <Link href={!storeData ? "/settings" : "/drinks"}>
              <Button bg="primary.500">{buttonActions}</Button>
            </Link>
          </VStack>
        </Center>
      </Flex>
    </>
  );
};

export default Home;
