import type { GetServerSideProps } from 'next';
import Head from 'next/head';
import { getProviders, signIn, signOut, useSession } from 'next-auth/react';
import { Button, Container, Heading } from '@chakra-ui/react';

type Provider = {
  id: string;
  name: string;
  type: string;
  icon: string;
  backgroundColor: string;
};

const SignIn = ({ providers }: { providers: Provider[] }) => {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>Auth</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="flex h-screen flex-col items-center justify-center gap-3">
        <Heading>You are currently {sessionData ? 'signed in' : 'signed out'}</Heading>
        <div className="flex flex-col gap-3">
          {!sessionData && (
            <>
              {Object.values(providers).map(provider => (
                <Button
                  key={provider.id}
                  colorScheme="primary"
                  onClick={() =>
                    signIn(provider.id, {
                      callbackUrl: `${window.location.origin}`,
                    })
                  }
                >
                  Sign in with {provider.name}
                </Button>
              ))}
            </>
          )}
          {sessionData && <Button onClick={() => signOut()}>Sign out</Button>}
        </div>
      </Container>
    </>
  );
};

export default SignIn;

export const getServerSideProps: GetServerSideProps = async () => {
  const providers = await getProviders();
  return {
    props: { providers },
  };
};
