import type { GetServerSideProps } from "next";
import Head from "next/head";
import { getProviders, signIn, signOut, useSession } from "next-auth/react";

type Provider = {
  id: string;
  name: string;
  type: string;
  icon: string;
  backgroundColor: string;
};

const SignIn = ({ providers }: { providers: Provider[] }) => {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>SignIn</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center justify-center">
        <div>
          {Object.values(providers).map((provider) => (
            <button
              key={provider.id}
              className="btn-primary btn"
              onClick={
                sessionData
                  ? () => signOut()
                  : () =>
                      signIn(provider.id, {
                        callbackUrl: `${window.location.origin}`,
                      })
              }
            >
              {sessionData ? "Sign out" : "Sign in with Google"}
            </button>
          ))}
        </div>
      </main>
    </>
  );
};

export default SignIn;

export const getServerSideProps: GetServerSideProps = async () => {
  const providers = await getProviders();
  return {
    props: { providers },
  };
};
