import type { GetServerSideProps } from "next";
import Head from "next/head";
import { getProviders, signIn, signOut, useSession } from "next-auth/react";
import { Button, Container } from "@chakra-ui/react";

type Provider = {
  id: string;
  name: string;
  type: string;
  icon: string;
  backgroundColor: string;
};

const SignIn = ({ providers }: { providers: Provider[] }) => {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>Auth</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="flex h-screen flex-col items-center justify-center gap-3">
        <div>
          {Object.values(providers).map((provider) => (
            <Button
              key={provider.id}
              onClick={
                sessionData
                  ? () => signOut()
                  : () =>
                      signIn(provider.id, {
                        callbackUrl: `${window.location.origin}`,
                      })
              }
            >
              {sessionData
                ? `Sign out of ${provider.name} `
                : `Sign in with ${provider.name}`}
            </Button>
          ))}
        </div>
      </Container>
    </>
  );
};

export default SignIn;

export const getServerSideProps: GetServerSideProps = async () => {
  const providers = await getProviders();
  return {
    props: { providers },
  };
};
