import { Button, Container, Text } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";

const AccessDenied = () => {
  return (
    <>
      <Head>
        <title>Access Denied</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        width={"100vw"}
        height={"100vh"}
        alignContent={"center"}
        justifyContent={"center"}
      >
        <Text>Access denied</Text>
        <Link href="/">
          <Button>Go home</Button>
        </Link>
      </Container>
    </>
  );
};

export default AccessDenied;
