import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "../../utils/api";
import { TextInput } from "../../components/TextInput";

const EditDrinkPage: NextPage = () => {
  const router = useRouter();
  const { id } = router.query as {
    id: string;
  };
  const { data, isLoading, error } = api.drinks.getDrinkById.useQuery(
    { id },
    {
      refetchOnWindowFocus: false,
    }
  );
  const handleChange = (e: React.FormEvent) => {
    console.log(e.currentTarget);
  };

  return (
    <>
      <Head>
        <title>Edit Drink Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen">
        <section className="container mx-auto py-10">
          <TextInput
            label="Title"
            value={data?.title ?? ""}
            onChange={(e) => handleChange(e)}
            required
          />
          {error && <p>error</p>}
          {isLoading && <p>Loading...</p>}
        </section>
      </main>
    </>
  );
};

export default EditDrinkPage;
